apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ownclouds.cloud.owncloud.com
spec:
  group: cloud.owncloud.com
  names:
    kind: Owncloud
    listKind: OwncloudList
    plural: ownclouds
    singular: owncloud
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
